Урок 1
RonzhinLeonid/GU_ASP.NET_Core_Web_API_Application pull request #1
Opened 2021-06-23 21:55 UTC by RonzhinLeonid

2021-07-05 14:30 UTC, vladimir-shmidt requested changes

2021-07-05 14:30 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
давай переключимся на dot net code вместо старого доброго 472

2021-07-05 14:38 UTC, vladimir-shmidt requested changes
нужно обновить проект или сделать новый - имеется в виду dot net solution так как сейчас используется старый .net framework вместо core

2021-07-05 14:38 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            WorkAsync("https://jsonplaceholder.typicode.com", "result1.json", 4, 20);
метод асинковый
значит результат будет таск
если результат таск то его нужно ожидать
если не ожидать то выполнение программы завершится раньше чем произойдет выполнение тасков

2021-07-05 14:38 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            WorkAsync("https://jsonplaceholder.typicode.com", "result1.json", 4, 20);
не стоит расчитывать что где то будет ReadLine в проекте благодаря которому работа будет выполнена
сейчас если его убрать то ничего работать не будет

2021-07-05 14:38 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            ServiceLoadPost.InitializeClient(apiUrl);
классы с публичными методами меняющими состояние внутренее это зло
значение урла должно передаваться через конструктор

2021-07-05 14:38 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/ServiceLoadPost.cs
> +            return tasks.Select(x => x.Result);
здесь все также буджет происходить ошибки
попробуй заменить id поста на что то вроде -1
тогда приложение схлопнится на такой задаче в момент чтения Result свойства у таски

2021-07-11 21:19 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
Переделе на .Core

2021-07-11 21:20 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            ServiceLoadPost.InitializeClient(apiUrl);
Исправил в новом проекте

2021-07-11 21:22 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            WorkAsync("https://jsonplaceholder.typicode.com", "result1.json", 4, 20);
Исправил в новом проекте, посмотрите, но что-то мне подсказывает что я всю асинхоронность убил

2021-07-11 21:25 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/ServiceLoadPost.cs
> +            return tasks.Select(x => x.Result);
пробовал разные вариант, у меня все время приложение отрабатывало, возвращая   
{
    "userId": 0,
    "id": 0,
    "title": null,
    "body": null
 }
в неверном id. Добавил принудительное создании пустого поста при id меньшем 1.
Так лучше?

2021-07-12 09:38 UTC, vladimir-shmidt requested changes

2021-07-12 09:38 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            WorkAsync("https://jsonplaceholder.typicode.com", "result1.json", 4, 20);
метод Main не асинковый а также нет ожидания у метода WorkAsync
да тут нет асинхронного выполнения

2021-07-12 09:38 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            WorkAsync("https://jsonplaceholder.typicode.com", "result1.json", 4, 20);
потом стоит подумать в сторону Task.WhenAll для вот этого спика вызовов из WorkAsync

2021-07-12 09:38 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            ServiceLoadPost.InitializeClient(apiUrl);
где посмотреть этот новый проект? и как понять что мой коммент тут был поправлен в новом проекте?

для код ревью через мерж реквесты нужно продолжать работать в той же ветке в который был сделан изначальный мерж реквест и добавлть изменения через комиты. Тогда будет видна вся итория и комменты которые были оставлены можно будет смапить с изменением и понять что было поправлено в связи с ним - коментраием

2021-07-12 19:42 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            ServiceLoadPost.InitializeClient(apiUrl);
Владимир, вот коммит в этой же ветке f3a8d18c1ecb69b4a8e60f6d39f58ac417578291

2021-07-12 19:53 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            ServiceLoadPost.InitializeClient(apiUrl);
к сожалению я не вижу изменения в само мерж реквесте

2021-07-12 19:56 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            ServiceLoadPost.InitializeClient(apiUrl);
к сожаление не вижу изменений в сама мерж реквесте, проверь пожалуйста https://github.com/RonzhinLeonid/GU_ASP.NET_Core_Web_API_Application/pull/1/files

2021-07-13 13:13 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +            ServiceLoadPost.InitializeClient(apiUrl);
у меня все по ссылке есть, внизу новые файлы в проекте Les1_V2, его пришлось создать, т.к. перевести из 472 в .core не было возможности

2021-07-14 12:44 UTC, vladimir-shmidt requested changes
уже лучше намного
коегде не хватает асинка с эвейтами поправь плиз

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/Program.cs
> +            Task.WaitAll();
WaitAll есть аргумент который нужно передавать. ерез него мы указываем какие задачи мы хотим ожидать

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/Program.cs
> +            Task.WaitAll();
осутсвует асинхронность нет await

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/Program.cs
> +            await Task.Run(() => WorkAsync(apiUrl, pathToFile, start, count));
в данном случае избыточно оборачить метод в запуск таска так как эвейт сразу будет дожидаться результатов выполнения. Достаточно сразу ожидать WorkAsync

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/Program.cs
> +        //private static async void WorkAsync(string apiUrl, string pathToFile, int start, int count)
закоменченный код лучше убирать сразу

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/Program.cs
> +            var posts = serviceLoadPost.LoadPostsAsync(start, count);
если операция LoadPostsAsync асинхронная то нет await

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/Program.cs
> +            SaveToFile.SaveFile(pathToFile, posts.Result);
работа с файлами также должна быть асинзроннойй

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/ServiceLoadPost.cs
> +            await Task.WhenAll(tasks);
стоит задуматься над устойчивость к ошибкам - что если одна из задача выполнится не корректно? Это не должно останавливать выполнение с успешными задачами

2021-07-14 12:44 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/ServiceLoadPost.cs
> +            if (id <= 0)
имолсь в виду что если передать -1 в качестве заначения для Client.GetAsync то пост не сможет скачаться и произойдет ошибка. Подобные ошибки могут не только из-за данных которые мы передаем в метод но и из-за того что отсутствовала сеть или сервер был отключен и тд
Эти моменты стоит предусматривать когда работаешь с сетевыми запросами

2021-07-19 08:02 UTC, vladimir-shmidt approved these changes
обработка ошибок ОК
асинки ОК
отлично

2021-07-19 08:02 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1_V2/SaveToFile.cs
> +            var stream = File.Create(pathToFile);
кстати Stream нужно закрывать после использования или использовать using со стримом

2021-07-19 20:13 UTC, merged