Les2
RonzhinLeonid/GU_ASP.NET_Core_Web_API_Application pull request #2
Opened 2021-07-13 16:28 UTC by RonzhinLeonid

2021-07-22 20:51 UTC, vladimir-shmidt requested changes
перепроверь пожулайста дифф
тут много лишнего - тяжело смотреть
нужно поменять базовый проект с MVC  на API

2021-07-22 20:51 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +    class Program
думаю этих изменений не должно быть в пулреквесте

2021-07-22 20:51 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/WebApi/Pages/Error.cshtml.cs
> +namespace WebApi.Pages
Pages вообще про другое

2021-07-22 20:51 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/WebApi/Pages/Error.cshtml.cs
> +    [IgnoreAntiforgeryToken]
похоже что использован не тот шаблон проекта
нужно  asp core api а здесь asp core mvc

2021-07-22 20:51 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/WebApi/Repository/CatsRepository.cs
> +            var catsList = _context.CreateDbContext();
стоит пересмотреть регистрацию ApplicationDataContext и использовать обычный  DBContext

2021-07-25 17:24 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/Program.cs
> +    class Program
Владимир, внес изменения https://github.com/RonzhinLeonid/GU_ASP.NET_Core_Web_API_Application/pull/2/commits/053837577a9c2381e6b2f14cf398a1f1d480a85b

2021-07-26 06:23 UTC, vladimir-shmidt requested changes
![Снимок экрана 2021-07-26 в 09 21 28](https://user-images.githubusercontent.com/1708303/126942349-d5a666cf-a9ea-4447-986d-6b89473ff821.png)
![Снимок экрана 2021-07-26 в 09 21 36](https://user-images.githubusercontent.com/1708303/126942369-2b4b8a2f-490e-44ef-99ca-af91c62ee851.png)
![Снимок экрана 2021-07-26 в 09 21 45](https://user-images.githubusercontent.com/1708303/126942380-dabb3bf6-b694-4346-a024-e0c7e4116462.png)

2021-07-26 06:23 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
.NETFramework,Version=v4.7.2 - устаревшая версия следует использовать .net core 3 и выше

2021-07-26 06:23 UTC, vladimir-shmidt commented on GU_ASP.NET_Core_Web_API_Application/Les1/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
после обновления фрейворка можно будет обновить файлы проектаов *.csproj
https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

2021-07-26 13:25 UTC, RonzhinLeonid commented on GU_ASP.NET_Core_Web_API_Application/Les1/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
Владимир, я это исправлял еще в 1м дз, посмотрите непосредственно файлы в последнем коммите, https://github.com/RonzhinLeonid/GU_ASP.NET_Core_Web_API_Application/pull/2/commits/053837577a9c2381e6b2f14cf398a1f1d480a85b
я могу его выделить в отедльный пулл, но на платформу прикрепить не смогу, там уже изменения закрыты

2021-09-01 07:54 UTC, vladimir-shmidt approved these changes
не хватает асинков на репозитории 
не забывай лелать асинк операции там где они есть

2021-09-03 10:00 UTC, merged